require: rubocop-rails
require: rubocop-rspec
# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3.1
  DisplayCopNames: true
  DisplayStyleGuide: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
